### ISSUE TITLE
Use the Github API's auth method for sending requests

### ISSUE THREAD

**Issue by Demfier** [Demfier/PUBGit#1]

**Comment by Demfier** [comment]
Will also enable to get email properly

**Comment by abiduzz420** [comment]
@Demfier I am interested to solve this issue. However I would be taking a 5 days or so, since I may not be able to fully devote time to working on this issue due to exams. I shall inform you about the progress I have made each day. Can I take up this issue, if that's fine ?

**Comment by Demfier** [comment]
@abiduzz420 - That's great.
I would suggest going through `load_gh_profile` in `Profile` class. Currently, a `get` request is made there which has to be modified to use the [OAuth method](https://developer.github.com/v3/#authentication) provided by github.

Let me know if you face any issues.

Cheers!

**Comment by abiduzz420** [comment]
Yeah sure @demfier I shall go through it. Thanks!

**Comment by abiduzz420** [comment]
@Demfier could you assign me this task ? Thanks!

**Comment by Demfier** [comment]
Sure, I've sent the collaborator-invite to you. Please self-assign this issue once you accept

**Comment by abiduzz420** [comment]
Heyy @Demfier I have made progress in getting oauth_token from Github server.

I am making a POST request using `requests` to get the OAuth Token
 
```
profile_req = requests.post('https://api.github.com/authorizations', data=data, auth=(username,password))
where
data = data = '{"scopes":["public_repo"],"client_id":":CLIENT_ID","client_secret":"CLIENT_SECRET"}'
```
The issue that is worrying me is **how should the developer provide his/her credentials?** In current implementation, the developer can simply pass `username` as a parameter and make REST call. How should we go about taking password through user input and in what format should we store it?

There are two other things that I would like to ask you apart from the above issue:
1. Where should we be storing the sensitive information like `client_id` & `client_secret` ? (Hint: I have read somewhere that we should be storing it as environment variable)
2. Secondly, I am thinking to implement interactive IO where in when the user creates `Profile` object, it would be asking his `username` and `password` from the cli. Your ideas ? 

Do let me know what you feel about these three issues.

Cheers!

**Comment by abiduzz420** [comment]
I think I am wrong about taking password and storing it as variable. I shall rework on how I implemented. The communication should be between the user and Github server without our app interfering in.

**Comment by abiduzz420** [comment]
Todo list:
- [x] Authorize Gitpub app. Got the OAuth token
- [ ] Use the OAuth token to authenticate user
- [ ] Github user authentication should be done from cli
- [ ]  Test the fetching of public repos

**Comment by Demfier** [comment]
@abiduzz420 - Good to hear the progress. So, coming to your queries:

1. Yeah, we don't need to use passwords, that won't be correct. However, we would need to store the OAuth-token to relieve the developer of the pain of putting it every time in the code and not to mention, it could expose his token publicly. You can use environment variables to store the token. Also, do keep give the dev an option to explicitly put an OAuth-token.

2. Regarding the IO, I guess you've already figured that out. However, there can be a minor variant, like you can ask for OAuth-token instead of password (if you can't find it neither from the env variable nor the dev has put it). This is a very general idea which I think is beyond the scope of this PR. File an issue regarding it in case you wish to work on it.

**Comment by abiduzz420** [comment]
@Demfier Thanks for the response!

I have created `settings.pyc` file which contains the `clientId` and `clientSecret` variables. I compiled `settings.py` and then moved the compiled file in the same directory as `gitpub.py`. This way the developer can reuse the `clientId` and `clientSecret` and also it is kept safe. Further if they would like to create their own OAuth app they could do that as well. I shall document the entire workflow in CONTRIBUTING.md file as a part of the PR.

**Comment by abiduzz420** [comment]
To generate OAuth token in the beginning, the developer will have to enter the username and password. Later when we call `GET /user` end point we will send username and OAuth token as `auth` parameters.

**Comment by Demfier** [comment]
@abiduzz420 
I don't think using a compiled file is a good way. There is a high possibility of data invalidation (like in cache-invalidation). So I would still recommend using environment-variables for storing the `clientId` and `clientSecret`.

Once you use env variables, I don't think there would be any need for the developer to enter username and password. Still, if the dev wants to generate the OAuth token using GitPub, there should be a provision for that.

Also, please create a PR so that I can suggest you better. Go through [CONTRIBUTING.md](https://github.com/demfier/gitpub/tree/master/CONTRIBUTING.md) just to avoid any unwanted nuisance.

Cheers!

**Comment by abiduzz420** [comment]
Okay @Demfier I will store `clientId` and `clientSecret` in the environment variables. I probably have to read about it. I will create the PR now and then resolve the issue of env. 
Yes I have gone through the `CONTRIBUTING.md` file. PR coming in few minutes. Thanks!
